### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Irostovsky** [ikechukwueze/Code-Task#1]
Hi @ikechukwueze 
I m Ivan from GuestReady. Thanks for the doing task.

I see the n+1 performance issue into https://github.com/ikechukwueze/Code-Task/blob/d76bfd24ea72df87bbe496bba8a62655f6536bdd/reservations/serializers.py#L14. Could you please improve the code to prevent extra requests to the database.

Thanks.

**Comment by ikechukwueze** [comment]
Overrode get_queryset to select_related foreign key field, Rental
Overrode list method to include subquery to Reservation.
Also added third party library that shows number of queries to database.
Only one query is now executed.
